# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lei/CNNIOT1/deeplib/Vivado_implementation/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_auto_pc_0/CNN_imp_auto_pc_0.xci
# IP: The module: 'CNN_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lei/CNNIOT1/deeplib/Vivado_implementation/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_auto_pc_0/CNN_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lei/CNNIOT1/deeplib/Vivado_implementation/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_auto_pc_0/CNN_imp_auto_pc_0.xci
# IP: The module: 'CNN_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lei/CNNIOT1/deeplib/Vivado_implementation/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_auto_pc_0/CNN_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
